// <auto-generated />
namespace eShop.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class name1939 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(name1939));
        
        string IMigrationMetadata.Id
        {
            get { return "201901161839332_name 1939"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
